### ISSUE TITLE
Event に numbering カラムが欲しい

### ISSUE THREAD

**Issue by haya14busa** [kawakubox/splathon#101]
API的にはまずナンバリングからどのイベントかとってくるので(indexされてる) numbering カラムがeventにほしいです。(あると嬉しい。とりあえずはいまのままでも動いている。)

numbering int32 か string? (10.5とかやりたくなってくるとstringにしておくとまだ対応できなくはない)

**Comment by kawakubox** [comment]
@haya14busa 

これ numbering だけだとちょっと意味づけしづらいので、

> code varchar
> numbering int32

とかで複合で unique にしてもいいですか？

今回の場合だと code は `splathon` で固定
numbering は 10 で参照してもらう感じっす。

**Comment by haya14busa** [comment]
LGTMです！ :+1:

**Comment by haya14busa** [comment]
[optional]
s/code/series_name/ とかでもいいかもと思いましたがcodeでもよさそう

**Comment by kawakubox** [comment]
たしかに code よりか series_name のほうが意味が膨らまなくてよさそうっすね。
