### ISSUE TITLE
参加者 (participants) 用のモデルを作成する

### ISSUE THREAD

**Issue by haya14busa** [kawakubox/splathon#99]
イカのようなテーブルが欲しいです。
(余裕あったらp-rしたかったがrails触ってなさ過ぎてすぐにはわからず；；)

Table: participants

id int64 (primary key, autoincrement か UUID)
event_id int64
slack_username string (e.g. kawakubo. 変わる可能性があるが参加登録時のもの)
slack_user_id string (e.g. U0XXXXXXX)
nickname string (e.g. かわくぼっくす)
fullname_kana string  (e.g. ヤマダハナコ)
company_name string
password string
icon_url string (slack icon image URL)

is_staff boolean
join_party boolean (懇親会に参加するか)
has_companion boolean (同伴者がいるかどうか)

team_id int64 (nullable, team_idがある場合playerであるとみなせる)
rank_splat_zones string (nullable, e.g. A+, X (2401~2500) )
rank_tower_control string (nullable)
rank_rainmaker string (nullable)
rank_clam_blitz string (nullable)
main_weapon string (nullable)
short_comment string (一言コメント e.g. 今日も一日頑張るぞい!)

**Comment by haya14busa** [comment]
追加

reception_done boolean (参加受付登録が完了したかどうか)


カラム多すぎるのでテーブル分けたほうがきれい説もありそうですがどうだろうか

**Comment by haya14busa** [comment]
reception_done_timestamp もあったほうが便利かもしれない(次から次へとでてきてもうしわけない...)

**Comment by haya14busa** [comment]
(password こっちが適当にgenerate してるとはいえ平文はダサいがsaltいれるだとか新API と現アプリでの整合性など面倒さがありそう)
raw_password とかにしておいてあとからイイ感じにできるようにしておいてもいいかも

**Comment by kawakubox** [comment]
●要件

- 出場チーム と 参加者を関連付けたい
- 参加者の受付記録をつけたい
    - 参加費
- 参加者パーソナル情報をストアしたい
    - ウデマエ
    - 推しブキ
    - Slack が持っている属性

*************************

スキーマ設計レベルでは、細かく分けておいて read only なところは view で提供すると API 層は楽か？？

**Comment by haya14busa** [comment]
APIからアップデートがはいるのは基本的には参加者の受付記録だけなので
このあたりがわかれてるのは嬉しいかもしれないですね。

**Comment by haya14busa** [comment]
すいません...

has_switch_dock boolean 

みたいなカラムが欲しかったにこちらにかくの忘れてました。
運用カバーでもよさそうだけどできたら欲しいです 🙇
